### PR TITLE
Add all stage columns to report

### PR DESCRIPTION
**Pull request by JB62**
Partial fix for #156 - still needs operator to be a name rather than a shortcode

### CODE REVIEW

**Comment by JB62** [comment]
Crap. It's missing the consignment too.

**Comment by JB62** [comment]
Didn't think you'd like it.

-----Original Message-----

**Comment by pjfl** [comment]
The first one was ok, I've almost merged that already. Will have the next bit done soon

**Comment by JB62** [comment]
I just wanted to have a fiddle so i understand what's going on.  Trying to code in the same style as you do to keep it all the same is a challenge though.

-----Original Message-----

**Pull request closed without merging**
